name: sentry_talker
description: An integration which adds support for recording log from the talker package.
version: 1.0.0+1


environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  sentry: ^8.14.0
  talker: ^4.7.0

dev_dependencies:
  coverage: ^1.3.0
  flutter_test:
    sdk: flutter
  meta: ^1.3.0
  mocktail: ^1.0.4
  test: ^1.21.1
  very_good_analysis: ">=6.0.0 <8.0.0"
  yaml: ^3.1.0 # needed for version match (code and pubspec)
